/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laundry;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sirly
 */
public class LaundryNotes extends javax.swing.JFrame {

    /**
     * Creates new form LaundryNotes
     */
    public LaundryNotes() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        
        tampilTanggal();
        
        hargaLaundry.disable();
        biayaAntar.disable();
        totalBayar.disable();
        kembalian.disable();
    }
    
    public void tampilTanggal(){
        Date tanggal = new Date();
        SimpleDateFormat aa = new SimpleDateFormat("dd-MM-yyyy");
        tanggalTransaksi.setText(aa.format(tanggal));
    }
    
    public void JumlahKarakterTransaksi(KeyEvent a) {
        if(noTransaksi.getText().length() == 4) {
            a.consume();
            JOptionPane.showMessageDialog(null,
                    "Maksimal 4 Karakter",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void FilterAngka(KeyEvent b) {
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,
                    "Masukkan hanya angka",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void JumlahKarakterBerat(KeyEvent c) {
        if(beratLaundry.getText().length() == 1) {
            c.consume();
            JOptionPane.showMessageDialog(null,
                    "Maksimal 9 kg",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tanggalTransaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenisLaundry = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lamaLaundry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        hargaLaundry = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        beratLaundry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pilihanJasa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jarakAntar = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        biayaAntar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        uangBayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LAUNDRY NOTES");

        jLabel2.setText("No. Transaksi");

        noTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noTransaksiKeyTyped(evt);
            }
        });

        jLabel3.setText("Tanggal");

        jLabel4.setText("Jenis Laundry");

        jenisLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuci", "Setrika" }));
        jenisLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaundryActionPerformed(evt);
            }
        });

        jLabel5.setText("Lama Laundry");

        lamaLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hari", "3 Hari", "5 Hari", "7 Hari" }));
        lamaLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaLaundryActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga Laundry");

        hargaLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaLaundryActionPerformed(evt);
            }
        });

        jLabel7.setText("Berat Laundry (kg)");

        beratLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratLaundryActionPerformed(evt);
            }
        });
        beratLaundry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                beratLaundryKeyTyped(evt);
            }
        });

        jLabel8.setText("Pilihan Jasa");

        pilihanJasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick Up", "Antar" }));
        pilihanJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanJasaActionPerformed(evt);
            }
        });

        jLabel9.setText("Jarak");

        jarakAntar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - 0,5 km", "0,6 - 1 km", "1,1 - 1,5 km", "1,6 - 2 km", "2,1 - 2,5 km", "2,6 - 3 km" }));
        jarakAntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarakAntarActionPerformed(evt);
            }
        });

        jLabel10.setText("Biaya Antar");

        jLabel11.setText("Total Bayar");

        jLabel12.setText("Uang Bayar");

        uangBayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                uangBayarFocusLost(evt);
            }
        });
        uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uangBayarKeyTyped(evt);
            }
        });

        jLabel13.setText("Kembalian");

        jButton1.setText("NEW NOTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("COUNT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(pilihanJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(biayaAntar)))
                        .addGap(102, 102, 102)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jarakAntar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jenisLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lamaLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalBayar)
                                    .addComponent(uangBayar)
                                    .addComponent(kembalian)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tanggalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hargaLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(beratLaundry))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tanggalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beratLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lamaLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pilihanJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jarakAntar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(biayaAntar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noTransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTransaksiKeyTyped
        // TODO add your handling code here:
        JumlahKarakterTransaksi(evt);
    }//GEN-LAST:event_noTransaksiKeyTyped

    private void jenisLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisLaundryActionPerformed
        // TODO add your handling code here:
        if(jenisLaundry.getSelectedItem() == "Cuci") {
            hargaLaundry.setText("20000");
            lamaLaundry.enable();
        }else if(jenisLaundry.getSelectedItem() == "Setrika") {
            hargaLaundry.setText("15000");
            lamaLaundry.disable();
        }
    }//GEN-LAST:event_jenisLaundryActionPerformed

    private void pilihanJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanJasaActionPerformed
        // TODO add your handling code here:
        if(pilihanJasa.getSelectedItem() == "Pick Up") {
            biayaAntar.setText("0");
            jarakAntar.disable();
        }else if(pilihanJasa.getSelectedItem() == "Antar") {
            jarakAntar.enable();
            biayaAntar.setText("2000");
        }
    }//GEN-LAST:event_pilihanJasaActionPerformed

    private void jarakAntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarakAntarActionPerformed
        // TODO add your handling code here:
        if(jarakAntar.getSelectedItem() == "0 - 0,5 km") {
            biayaAntar.setText("2000");
        }else if(jarakAntar.getSelectedItem() == "0,6 - 1 km") {
            biayaAntar.setText("3000");
        }else if(jarakAntar.getSelectedItem() == "1,1 - 1,5 km") {
            biayaAntar.setText("4000");
        }else if(jarakAntar.getSelectedItem() == "1,6 - 2 km") {
            biayaAntar.setText("5000");
        }else if(jarakAntar.getSelectedItem() == "2,1 - 2,5 km") {
            biayaAntar.setText("6000");
        }
        else if(jarakAntar.getSelectedItem() == "2,6 - 3 km") {
            biayaAntar.setText("7000");
        }
    }//GEN-LAST:event_jarakAntarActionPerformed

    private void hargaLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaLaundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaLaundryActionPerformed

    private void lamaLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaLaundryActionPerformed
        // TODO add your handling code here:
        if(lamaLaundry.getSelectedItem() == "1 Hari") {
            hargaLaundry.setText("30000");
        }else if(lamaLaundry.getSelectedItem() == "3 Hari") {
            hargaLaundry.setText("27000");
        }else if(lamaLaundry.getSelectedItem() == "5 Hari") {
            hargaLaundry.setText("25000");
        }else if(lamaLaundry.getSelectedItem() == "7 Hari") {
            hargaLaundry.setText("20000");
        }
    }//GEN-LAST:event_lamaLaundryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        noTransaksi.setText("");
        hargaLaundry.setText("");
        beratLaundry.setText("");
        biayaAntar.setText("");
        totalBayar.setText("");
        uangBayar.setText("");
        kembalian.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,
            "Apakah yakin akan keluar?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int hargaAkhirLaundry = Integer.parseInt(hargaLaundry.getText());
        int berat = Integer.parseInt(beratLaundry.getText());
        int hargaAkhirAntar = Integer.parseInt(biayaAntar.getText());
        int totalAkhirBayar = 0;
        
        totalAkhirBayar = ((hargaAkhirLaundry * berat) + hargaAkhirAntar);
        totalBayar.setText(Integer.valueOf(totalAkhirBayar).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uangBayarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uangBayarFocusLost
        // TODO add your handling code here:
        int cekTotalBayar = Integer.parseInt(totalBayar.getText());
        int cekBayar = Integer.parseInt(uangBayar.getText());
        
        if(cekBayar < cekTotalBayar) {
            JOptionPane.showMessageDialog(null,
                    "Uang pembayaran kurang",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            int hitungKembalian = 0;
            hitungKembalian = cekBayar - cekTotalBayar;
            kembalian.setText(Integer.valueOf(hitungKembalian).toString());
        }
    }//GEN-LAST:event_uangBayarFocusLost

    private void beratLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratLaundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratLaundryActionPerformed

    private void beratLaundryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratLaundryKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
        JumlahKarakterBerat(evt);
    }//GEN-LAST:event_beratLaundryKeyTyped

    private void uangBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_uangBayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaundryNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaundryNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaundryNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaundryNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaundryNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratLaundry;
    private javax.swing.JTextField biayaAntar;
    private javax.swing.JTextField hargaLaundry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jarakAntar;
    private javax.swing.JComboBox<String> jenisLaundry;
    private javax.swing.JTextField kembalian;
    private javax.swing.JComboBox<String> lamaLaundry;
    private javax.swing.JTextField noTransaksi;
    private javax.swing.JComboBox<String> pilihanJasa;
    private javax.swing.JTextField tanggalTransaksi;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField uangBayar;
    // End of variables declaration//GEN-END:variables
}
